export const query = (sparql) => {
  return fetch(`http://dbpedia.org/sparql?query=${encodeURIComponent(sparql)}&format=${encodeURIComponent('application/sparql-results+json')}`)
         .then(r => {
           if (r.status == 200) {
             return r.json();
           } else {
             return r.text().then((error) => Promise.reject({message: error}));
           }
         })
}

export const getPopulationQuery = (countryCode) =>
  countryCodeMap[countryCode]
  ? `SELECT * WHERE {\n\tOPTIONAL {<${countryCodeMap[countryCode]}> dbo:populationTotal ?populationTotal.}\n}`
  : null;

export const getCountryPropertiesQuery = (countryResource) =>
  `SELECT * WHERE {\n\t<${countryResource}> ?property ?object.\n}`

// DBpedia does not have any standard for getting countries from country codes
// This was mostly done using dbo:wikiPageRedirects via /tools/country-map-builder.js
export const countryCodeMap = {
  "BE": "http://dbpedia.org/resource/Belgium",
  "BD": "http://dbpedia.org/resource/Bangladesh",
  "BG": "http://dbpedia.org/resource/Bulgaria",
  "BF": "http://dbpedia.org/resource/Burkina_Faso",
  "BA": "http://dbpedia.org/resource/Bosnia_and_Herzegovina",
  "BN": "http://dbpedia.org/resource/Brunei",
  "BO": "http://dbpedia.org/resource/Bolivia",
  "JP": "http://dbpedia.org/resource/Japan",
  "BI": "http://dbpedia.org/resource/Burundi",
  "BJ": "http://dbpedia.org/resource/Benin",
  "JM": "http://dbpedia.org/resource/Jamaica",
  "BT": "http://dbpedia.org/resource/Bhutan",
  "BR": "http://dbpedia.org/resource/Brazil",
  "BS": "http://dbpedia.org/resource/The_Bahamas",
  "BY": "http://dbpedia.org/resource/Belarus",
  "BZ": "http://dbpedia.org/resource/Belize",
  "RU": "http://dbpedia.org/resource/Russia",
  "RW": "http://dbpedia.org/resource/Rwanda",
  "RS": "http://dbpedia.org/resource/Serbia",
  "TL": "http://dbpedia.org/resource/East_Timor",
  "TM": "http://dbpedia.org/resource/Turkmenistan",
  "TJ": "http://dbpedia.org/resource/Tajikistan",
  "RO": "http://dbpedia.org/resource/Romania",
  "GW": "http://dbpedia.org/resource/Guinea-Bissau",
  "GT": "http://dbpedia.org/resource/Guatemala",
  "GR": "http://dbpedia.org/resource/Greece",
  "GQ": "http://dbpedia.org/resource/Equatorial_Guinea",
  "GY": "http://dbpedia.org/resource/Guyana",
  "GE": "http://dbpedia.org/resource/Georgia_(country)",
  "GB": "http://dbpedia.org/resource/United_Kingdom",
  "GA": "http://dbpedia.org/resource/Gabon",
  "GN": "http://dbpedia.org/resource/Guinea",
  "GM": "http://dbpedia.org/resource/The_Gambia",
  "GL": "http://dbpedia.org/resource/Greenland",
  "GH": "http://dbpedia.org/resource/Ghana",
  "TN": "http://dbpedia.org/resource/Tunisia",
  "OM": "http://dbpedia.org/resource/Oman",
  "JO": "http://dbpedia.org/resource/Jordan",
  "HR": "http://dbpedia.org/resource/Croatia",
  "HT": "http://dbpedia.org/resource/Haiti",
  "HU": "http://dbpedia.org/resource/Hungary",
  "HN": "http://dbpedia.org/resource/Honduras",
  "PR": "http://dbpedia.org/resource/Puerto_Rico",
  "PS": "http://dbpedia.org/resource/State_of_Palestine",
  "PT": "http://dbpedia.org/resource/Portugal",
  "PY": "http://dbpedia.org/resource/Paraguay",
  "PA": "http://dbpedia.org/resource/Panama",
  "PG": "http://dbpedia.org/resource/Papua_New_Guinea",
  "PE": "http://dbpedia.org/resource/Peru",
  "PK": "http://dbpedia.org/resource/Pakistan",
  "PH": "http://dbpedia.org/resource/Philippines",
  "PL": "http://dbpedia.org/resource/Poland",
  "ZM": "http://dbpedia.org/resource/Zambia",
  "EE": "http://dbpedia.org/resource/Estonia",
  "EG": "http://dbpedia.org/resource/Egypt",
  "ZA": "http://dbpedia.org/resource/South_Africa",
  "EC": "http://dbpedia.org/resource/Ecuador",
  "IT": "http://dbpedia.org/resource/Italy",
  "VN": "http://dbpedia.org/resource/Vietnam",
  "SB": "http://dbpedia.org/resource/Solomon_Islands",
  "SO": "http://dbpedia.org/resource/Somalia",
  "ET": "http://dbpedia.org/resource/Ethiopia",
  "ZW": "http://dbpedia.org/resource/Zimbabwe",
  "ES": "http://dbpedia.org/resource/Spain",
  "ER": "http://dbpedia.org/resource/Eritrea",
  "ME": "http://dbpedia.org/resource/Montenegro",
  "MD": "http://dbpedia.org/resource/Moldova",
  "MG": "http://dbpedia.org/resource/Madagascar",
  "MA": "http://dbpedia.org/resource/Morocco",
  "UZ": "http://dbpedia.org/resource/Uzbekistan",
  "MM": "http://dbpedia.org/resource/Myanmar",
  "ML": "http://dbpedia.org/resource/Mali",
  "MN": "http://dbpedia.org/resource/Mongolia",
  "MK": "http://dbpedia.org/resource/Republic_of_Macedonia",
  "MW": "http://dbpedia.org/resource/Malawi",
  "MR": "http://dbpedia.org/resource/Mauritania",
  "MY": "http://dbpedia.org/resource/Malaysia",
  "MX": "http://dbpedia.org/resource/Mexico",
  "IL": "http://dbpedia.org/resource/Israel",
  "FR": "http://dbpedia.org/resource/France",
  "FI": "http://dbpedia.org/resource/Finland",
  "FJ": "http://dbpedia.org/resource/Fiji",
  "FK": "http://dbpedia.org/resource/Falkland_Islands",
  "NI": "http://dbpedia.org/resource/Nicaragua",
  "NL": "http://dbpedia.org/resource/Netherlands",
  "NO": "http://dbpedia.org/resource/Norway",
  "NA": "http://dbpedia.org/resource/Namibia",
  "VU": "http://dbpedia.org/resource/Vanuatu",
  "NC": "http://dbpedia.org/resource/New_Caledonia",
  "NE": "http://dbpedia.org/resource/Niger",
  "NG": "http://dbpedia.org/resource/Nigeria",
  "NZ": "http://dbpedia.org/resource/New_Zealand",
  "NP": "http://dbpedia.org/resource/Nepal",
  "CI": "http://dbpedia.org/resource/Ivory_Coast",
  "CH": "http://dbpedia.org/resource/Switzerland",
  "CO": "http://dbpedia.org/resource/Colombia",
  "CN": "http://dbpedia.org/resource/China",
  "CM": "http://dbpedia.org/resource/Cameroon",
  "CL": "http://dbpedia.org/resource/Chile",
  "CA": "http://dbpedia.org/resource/Canada",
  "CG": "http://dbpedia.org/resource/Republic_of_the_Congo",
  "CF": "http://dbpedia.org/resource/Central_African_Republic",
  "CD": "http://dbpedia.org/resource/Democratic_Republic_of_the_Congo",
  "CZ": "http://dbpedia.org/resource/Czech_Republic",
  "CY": "http://dbpedia.org/resource/Cyprus",
  "CR": "http://dbpedia.org/resource/Costa_Rica",
  "KE": "http://dbpedia.org/resource/Kenya",
  "SS": "http://dbpedia.org/resource/South_Sudan",
  "CU": "http://dbpedia.org/resource/Cuba",
  "SZ": "http://dbpedia.org/resource/Swaziland",
  "SY": "http://dbpedia.org/resource/Syria",
  "KG": "http://dbpedia.org/resource/Kyrgyzstan",
  "SR": "http://dbpedia.org/resource/Suriname",
  "KH": "http://dbpedia.org/resource/Cambodia",
  "SV": "http://dbpedia.org/resource/El_Salvador",
  "SK": "http://dbpedia.org/resource/Slovakia",
  "KR": "http://dbpedia.org/resource/South_Korea",
  "SI": "http://dbpedia.org/resource/Slovenia",
  "KP": "http://dbpedia.org/resource/North_Korea",
  "KW": "http://dbpedia.org/resource/Kuwait",
  "SN": "http://dbpedia.org/resource/Senegal",
  "KZ": "http://dbpedia.org/resource/Kazakhstan",
  "SA": "http://dbpedia.org/resource/Saudi_Arabia",
  "SL": "http://dbpedia.org/resource/Sierra_Leone",
  "SE": "http://dbpedia.org/resource/Sweden",
  "SD": "http://dbpedia.org/resource/Sudan",
  "DO": "http://dbpedia.org/resource/Dominican_Republic",
  "DJ": "http://dbpedia.org/resource/Djibouti",
  "DK": "http://dbpedia.org/resource/Denmark",
  "DE": "http://dbpedia.org/resource/Germany",
  "YE": "http://dbpedia.org/resource/Yemen",
  "DZ": "http://dbpedia.org/resource/Algeria",
  "US": "http://dbpedia.org/resource/United_States",
  "UY": "http://dbpedia.org/resource/Uruguay",
  "LB": "http://dbpedia.org/resource/Lebanon",
  "LA": "http://dbpedia.org/resource/Laos",
  "TW": "http://dbpedia.org/resource/Taiwan",
  "TT": "http://dbpedia.org/resource/Trinidad_and_Tobago",
  "TR": "http://dbpedia.org/resource/Turkey",
  "LK": "http://dbpedia.org/resource/Sri_Lanka",
  "LV": "http://dbpedia.org/resource/Latvia",
  "LT": "http://dbpedia.org/resource/Lithuania",
  "LU": "http://dbpedia.org/resource/Luxembourg",
  "LR": "http://dbpedia.org/resource/Liberia",
  "TH": "http://dbpedia.org/resource/Thailand",
  "TF": "http://dbpedia.org/resource/French_Southern_and_Antarctic_Lands",
  "LS": "http://dbpedia.org/resource/Lesotho",
  "TG": "http://dbpedia.org/resource/Togo",
  "TD": "http://dbpedia.org/resource/Chad",
  "LY": "http://dbpedia.org/resource/Libya",
  "AE": "http://dbpedia.org/resource/United_Arab_Emirates",
  "VE": "http://dbpedia.org/resource/Venezuela",
  "AF": "http://dbpedia.org/resource/Afghanistan",
  "IQ": "http://dbpedia.org/resource/Iraq",
  "IS": "http://dbpedia.org/resource/Iceland",
  "IR": "http://dbpedia.org/resource/Iran",
  "AM": "http://dbpedia.org/resource/Armenia",
  "AL": "http://dbpedia.org/resource/Albania",
  "AR": "http://dbpedia.org/resource/Argentina",
  "AO": "http://dbpedia.org/resource/Angola",
  "AU": "http://dbpedia.org/resource/Australia",
  "AT": "http://dbpedia.org/resource/Austria",
  "IN": "http://dbpedia.org/resource/India",
  "TZ": "http://dbpedia.org/resource/Tanzania",
  "AZ": "http://dbpedia.org/resource/Azerbaijan",
  "IE": "http://dbpedia.org/resource/Republic_of_Ireland",
  "ID": "http://dbpedia.org/resource/Indonesia",
  "UA": "http://dbpedia.org/resource/Ukraine",
  "QA": "http://dbpedia.org/resource/Qatar",
  "MZ": "http://dbpedia.org/resource/Mozambique",

  //Note: these were added manually as they are not of type dbo:Country
  "BW": "http://dbpedia.org/page/Botswana",
  "EH": "http://dbpedia.org/page/Western_Sahara",
  "UG": "http://dbpedia.org/page/Uganda",
  "XC": "http://dbpedia.org/page/Northern_Cyprus",
  "XK": "http://dbpedia.org/page/Kosovo",
  "XS": "http://dbpedia.org/page/Somaliland"
};
